export interface ToolMeta {
  id: string;
  name: string;
  route: string;
  category: 'json' | 'yaml' | 'xml' | 'markup' | 'security' | 'encoding';
  description: string;
  shortDescription: string;
  icon: string;
  keywords: string[];
  sampleInput: string;
  sampleOutput: string;
  faq: { q: string; a: string }[];
  relatedTools: string[];
  seoH1: string;
  seoExtra: {
    comparisonTitle: string;
    comparisonRows: { label: string; left: string; right: string }[];
    commonErrors: string[];
    useCases: string[];
    longDescription: string;
  };
}

export const TOOLS: ToolMeta[] = [
  {
    id: 'json-formatter',
    name: 'JSON Formatter',
    route: '/json-formatter',
    category: 'json',
    description:
      'Format and beautify your JSON data with proper indentation. Paste raw JSON and get a clean, readable output instantly.',
    shortDescription: 'Beautify JSON with proper indentation',
    icon: '{ }',
    keywords: ['json', 'formatter', 'beautify', 'prettify', 'indent', 'pretty print'],
    sampleInput: '{"name":"John Doe","age":30,"address":{"street":"123 Main St","city":"Springfield"},"hobbies":["reading","gaming","cooking"]}',
    sampleOutput: '{\n  "name": "John Doe",\n  "age": 30,\n  "address": {\n    "street": "123 Main St",\n    "city": "Springfield"\n  },\n  "hobbies": [\n    "reading",\n    "gaming",\n    "cooking"\n  ]\n}',
    seoH1: 'JSON Formatter — Beautify & Pretty Print JSON Online Free',
    seoExtra: {
      comparisonTitle: 'Formatted vs Minified JSON',
      comparisonRows: [
        { label: 'Readability', left: 'Easy to read and debug', right: 'Hard to read' },
        { label: 'File Size', left: 'Larger due to whitespace', right: 'Smallest possible' },
        { label: 'Use Case', left: 'Development, debugging, code review', right: 'Production, APIs, storage' },
        { label: 'Indentation', left: '2 or 4 spaces per level', right: 'No indentation' },
        { label: 'Line Breaks', left: 'One property per line', right: 'Single line' },
      ],
      commonErrors: [
        'Trailing commas after the last property in an object or array are not valid JSON',
        'Single quotes around strings — JSON requires double quotes',
        'Unquoted property keys — all JSON keys must be wrapped in double quotes',
        'Missing commas between properties or array elements',
        'Comments (// or /* */) are not allowed in standard JSON',
      ],
      useCases: [
        'Debugging API responses by making minified JSON readable',
        'Preparing JSON configuration files for code review',
        'Formatting database exports for analysis',
        'Making JSON payloads readable in documentation',
        'Cleaning up JSON output from command-line tools',
      ],
      longDescription: 'JSON (JavaScript Object Notation) is the most widely used data interchange format on the web. When JSON is transmitted over networks or stored in databases, it is often minified to save bandwidth. Our JSON Formatter tool takes compressed or unformatted JSON and transforms it into a clean, indented structure with 2-space indentation, proper line breaks, and consistent formatting. This makes it easy to visually inspect nested objects, debug API responses, and prepare configuration files for version control. The formatter handles all valid JSON types including strings, numbers, booleans, null values, arrays, and deeply nested objects. Processing happens entirely in your browser using the native JSON.parse and JSON.stringify APIs, so your data remains private and never touches any server.',
    },
    faq: [
      {
        q: 'What is JSON Formatter?',
        a: 'JSON Formatter is a free online tool that takes raw or minified JSON data and formats it with proper indentation and line breaks, making it easy to read and debug.',
      },
      {
        q: 'How do I format JSON online?',
        a: 'Paste your JSON into the editor on the left panel and press Ctrl+Enter or click the Run button. The formatted output with proper indentation appears instantly in the right panel.',
      },
      {
        q: 'Is my JSON data safe when using this tool?',
        a: 'Yes. All processing happens entirely in your browser using JavaScript. No data is ever sent to any server. You can verify this by checking the Network tab in your browser DevTools.',
      },
      {
        q: 'What indentation does the JSON formatter use?',
        a: 'The formatter uses 2-space indentation by default. Each nested level of objects and arrays is indented by 2 additional spaces for clear visual hierarchy.',
      },
      {
        q: 'Can I format invalid JSON?',
        a: 'No. The formatter requires valid JSON as input. If your JSON has syntax errors like trailing commas, unquoted keys, or single quotes, you will see an error message. Use our JSON Validator to identify the exact errors first.',
      },
    ],
    relatedTools: ['json-validator', 'json-minifier', 'json-to-xml'],
  },
  {
    id: 'json-validator',
    name: 'JSON Validator',
    route: '/json-validator',
    category: 'json',
    description:
      'Validate your JSON data and get detailed error messages with line numbers. Instantly find syntax errors in any JSON string.',
    shortDescription: 'Validate JSON and find syntax errors',
    icon: '✓',
    keywords: ['json', 'validator', 'lint', 'check', 'syntax', 'verify'],
    sampleInput: '{"name": "Test", "items": [1, 2, 3], "valid": true}',
    sampleOutput: '✓ Valid JSON',
    seoH1: 'JSON Validator — Check & Validate JSON Syntax Online Free',
    seoExtra: {
      comparisonTitle: 'JSON Validator vs JSON Formatter',
      comparisonRows: [
        { label: 'Purpose', left: 'Checks if JSON is syntactically correct', right: 'Reformats valid JSON with indentation' },
        { label: 'Output', left: 'Valid/Invalid status with error details', right: 'Reformatted JSON string' },
        { label: 'Modifies Input', left: 'No — read-only check', right: 'Yes — reformats whitespace' },
        { label: 'Error Reporting', left: 'Detailed error messages with position', right: 'Only shows parsing errors' },
        { label: 'Best For', left: 'Debugging broken JSON', right: 'Making valid JSON readable' },
      ],
      commonErrors: [
        'Trailing comma after the last element — remove the comma before the closing bracket',
        'Single quotes instead of double quotes — JSON strictly requires double quotes for strings and keys',
        'Missing closing brackets — every { must have a matching } and every [ must have a matching ]',
        'Undefined or NaN values — these are not valid JSON; use null instead',
        'Unescaped special characters in strings — backslashes, newlines, and tabs must be escaped',
      ],
      useCases: [
        'Debugging API response errors before processing in your application',
        'Validating JSON configuration files before deployment',
        'Checking JSON payloads before sending POST/PUT requests',
        'Verifying JSON data exported from databases or spreadsheets',
        'Testing JSON output from code generators and templating systems',
      ],
      longDescription: 'JSON validation is a critical step in any development workflow that involves data interchange. Even a single misplaced comma, missing bracket, or unquoted key can cause an entire API request to fail or a configuration file to be rejected. Our JSON Validator parses your input using the browser\'s native JSON.parse engine and reports the exact error type and character position when validation fails. Unlike basic syntax checkers, this tool provides human-readable error messages that help you pinpoint problems quickly. For valid JSON, you get a clear confirmation message. The validator handles all JSON data types and structures including deeply nested objects, large arrays, Unicode characters, and escaped sequences. Because all validation happens in your browser, there is zero latency and your sensitive data never leaves your machine.',
    },
    faq: [
      {
        q: 'What is JSON Validator?',
        a: 'JSON Validator is a free online tool that checks whether your JSON string is syntactically correct. It highlights exact error positions with detailed messages to help you fix issues quickly.',
      },
      {
        q: 'What types of errors can it detect?',
        a: 'It detects all JSON syntax errors including missing brackets, trailing commas, unquoted keys, invalid escape sequences, duplicate keys, and improperly nested structures.',
      },
      {
        q: 'Does JSON Validator modify my data?',
        a: 'No. The validator is read-only — it only checks your JSON for errors and never changes your input data. If you want to reformat your JSON, use the JSON Formatter.',
      },
      {
        q: 'What is the difference between JSON Validator and JSON Lint?',
        a: 'JSON Lint is another name for JSON validation. Our JSON Validator performs the same function as JSONLint — it parses your JSON and reports syntax errors. Both terms refer to checking JSON for correctness.',
      },
      {
        q: 'Can I validate very large JSON files?',
        a: 'Yes. Since validation runs in your browser, it can handle large JSON files limited only by your browser\'s memory. For files over 10MB, processing may take a few seconds.',
      },
    ],
    relatedTools: ['json-formatter', 'json-minifier', 'json-to-xml'],
  },
  {
    id: 'json-minifier',
    name: 'JSON Minifier',
    route: '/json-minifier',
    category: 'json',
    description:
      'Minify JSON by removing all whitespace and line breaks. Reduce file size for storage, APIs, and network transmission.',
    shortDescription: 'Minify JSON to reduce size',
    icon: '⊟',
    keywords: ['json', 'minifier', 'compress', 'compact', 'minimize', 'uglify'],
    sampleInput: '{\n  "name": "John Doe",\n  "age": 30,\n  "address": {\n    "street": "123 Main St",\n    "city": "Springfield"\n  }\n}',
    sampleOutput: '{"name":"John Doe","age":30,"address":{"street":"123 Main St","city":"Springfield"}}',
    seoH1: 'JSON Minifier — Compress & Minify JSON Online Free',
    seoExtra: {
      comparisonTitle: 'Minified vs Formatted JSON',
      comparisonRows: [
        { label: 'File Size', left: 'Smallest possible', right: 'Larger due to whitespace' },
        { label: 'Readability', left: 'Not human-readable', right: 'Easy to read' },
        { label: 'Use Case', left: 'APIs, storage, production', right: 'Development, debugging' },
        { label: 'Bandwidth', left: 'Reduces network transfer', right: 'Uses more bandwidth' },
        { label: 'Performance', left: 'Faster parsing (fewer characters)', right: 'Slightly slower parsing' },
      ],
      commonErrors: [
        'Input must be valid JSON — minification fails if the JSON has syntax errors',
        'Minification does not remove data — it only strips whitespace characters',
        'Unicode characters are preserved exactly as they appear in the original',
        'Numeric precision is maintained — no rounding or truncation occurs',
        'Empty objects {} and empty arrays [] remain unchanged after minification',
      ],
      useCases: [
        'Reducing JSON payload size before sending API requests',
        'Compressing JSON configuration files for production deployment',
        'Minimizing localStorage usage in web applications',
        'Preparing JSON data for embedding in HTML or JavaScript',
        'Reducing bandwidth costs for JSON-heavy API endpoints',
      ],
      longDescription: 'JSON minification is the process of removing all unnecessary whitespace, line breaks, and indentation from a JSON string while preserving its data integrity. This produces the most compact valid JSON representation, which is critical for reducing bandwidth usage in API responses, minimizing storage costs in databases, and improving parse performance in client-side applications. Our JSON Minifier processes your data entirely in the browser — it parses the JSON into a JavaScript object and re-serializes it without any formatting. The output is guaranteed to be valid JSON with identical data to the original. Typical size reductions range from 20% to 60% depending on the original formatting. For production APIs that serve millions of requests, even small per-response savings add up to significant bandwidth and cost reductions.',
    },
    faq: [
      {
        q: 'What is JSON Minifier?',
        a: 'JSON Minifier is a free tool that compresses JSON by stripping all unnecessary whitespace, line breaks, and indentation to produce the smallest valid JSON string possible.',
      },
      {
        q: 'Why should I minify JSON?',
        a: 'Minified JSON uses less bandwidth and storage. It is ideal for API responses, configuration payloads, embedding in scripts, and any scenario where file size matters.',
      },
      {
        q: 'Does minification change my data?',
        a: 'No. Only whitespace characters are removed. All data values, structure, key names, and nesting remain identical. You can always re-format minified JSON back to readable form.',
      },
      {
        q: 'How much smaller does JSON get after minification?',
        a: 'Typical size reductions range from 20% to 60%, depending on how much indentation and formatting the original JSON contained. Deeply nested JSON with large indentation sees the biggest reductions.',
      },
      {
        q: 'Is JSON Minifier the same as JSON Compressor?',
        a: 'JSON minification and compression are often used interchangeably, but technically minification removes whitespace while compression (like gzip) uses algorithms to further reduce size. This tool performs minification.',
      },
    ],
    relatedTools: ['json-formatter', 'json-validator', 'json-to-xml'],
  },
  {
    id: 'json-to-xml',
    name: 'JSON to XML',
    route: '/json-to-xml',
    category: 'json',
    description:
      'Convert JSON data to well-formed XML. Supports nested objects, arrays, and all JSON value types with proper indentation.',
    shortDescription: 'Convert JSON to XML format',
    icon: '⇄',
    keywords: ['json', 'xml', 'convert', 'transform', 'export', 'converter'],
    sampleInput: '{"bookstore":{"book":[{"title":"The Great Gatsby","author":"F. Scott Fitzgerald","year":1925},{"title":"1984","author":"George Orwell","year":1949}]}}',
    sampleOutput: '<?xml version="1.0" encoding="UTF-8"?>\n<root>\n  <bookstore>\n    <book>\n      <item_0>\n        <title>The Great Gatsby</title>\n        <author>F. Scott Fitzgerald</author>\n        <year>1925</year>\n      </item_0>\n    </book>\n  </bookstore>\n</root>',
    seoH1: 'JSON to XML Converter — Convert JSON to XML Online Free',
    seoExtra: {
      comparisonTitle: 'JSON vs XML Comparison',
      comparisonRows: [
        { label: 'Syntax', left: 'Key-value pairs, arrays', right: 'Tags with attributes' },
        { label: 'Readability', left: 'More compact', right: 'More verbose' },
        { label: 'Data Types', left: 'String, number, boolean, null, array, object', right: 'All text (needs schema for types)' },
        { label: 'File Size', left: 'Smaller', right: 'Larger due to closing tags' },
        { label: 'Parsing', left: 'Native in JavaScript', right: 'Requires XML parser' },
        { label: 'Comments', left: 'Not supported', right: 'Supported' },
      ],
      commonErrors: [
        'Invalid JSON input — make sure your JSON is valid before converting',
        'Keys with special characters get sanitized (spaces become underscores)',
        'Arrays produce <item_0>, <item_1> elements — not repeated same-name tags',
        'Null values produce self-closing tags like <field />',
        'Root element is always <root> — rename after export if needed',
      ],
      useCases: [
        'Migrating data from JSON-based APIs to XML-based legacy systems',
        'Generating XML feeds from JSON data sources',
        'Converting JSON configuration to XML format for Java/.NET applications',
        'Creating SOAP payloads from RESTful JSON responses',
        'Exporting data for systems that only accept XML input',
      ],
      longDescription: 'JSON and XML are the two most common data interchange formats used in software development. While JSON dominates modern web APIs due to its compact syntax and native JavaScript support, many enterprise systems, SOAP web services, and legacy applications still require XML. Our JSON to XML converter bridges this gap by transforming any valid JSON structure into well-formed, properly indented XML. The conversion handles all JSON types: strings become text content, numbers and booleans become text nodes, null values produce self-closing tags, arrays are wrapped with indexed child elements, and nested objects create hierarchical XML elements. Special characters in keys are automatically sanitized to produce valid XML element names. The output includes an XML declaration header and uses 2-space indentation for readability.',
    },
    faq: [
      {
        q: 'How does JSON to XML conversion work?',
        a: 'Each JSON key becomes an XML element name. String, number, and boolean values become text content. Arrays are wrapped in a parent element with numbered child items (item_0, item_1). Null values produce self-closing tags.',
      },
      {
        q: 'Does it handle deeply nested JSON?',
        a: 'Yes. The converter recursively processes all levels of nesting. Deeply nested objects and arrays are converted into properly indented, hierarchical XML elements.',
      },
      {
        q: 'Can I convert XML back to JSON?',
        a: 'This tool currently only converts JSON to XML. An XML to JSON converter is planned for a future release. You can use other tools in the meantime for the reverse conversion.',
      },
      {
        q: 'What happens to special characters in JSON keys?',
        a: 'JSON keys containing spaces, dots, or other special characters are automatically sanitized. Non-alphanumeric characters (except hyphens and underscores) are replaced with underscores to produce valid XML element names.',
      },
      {
        q: 'Is the output valid XML?',
        a: 'Yes. The output includes a proper XML declaration (<?xml version="1.0" encoding="UTF-8"?>) and all elements are properly nested and closed. Special characters in values are escaped using XML entities (&amp; &lt; &gt;).',
      },
    ],
    relatedTools: ['xml-to-json', 'json-formatter', 'json-validator'],
  },
  {
    id: 'base64',
    name: 'Base64 Encode/Decode',
    route: '/base64',
    category: 'encoding',
    description:
      'Encode text to Base64 or decode Base64 strings back to plain text. Supports full UTF-8 encoding for multi-byte characters.',
    shortDescription: 'Encode and decode Base64 strings',
    icon: 'B64',
    keywords: ['base64', 'encode', 'decode', 'binary', 'text', 'encoder', 'decoder'],
    sampleInput: 'Hello, World! This is a test string for Base64 encoding.',
    sampleOutput: 'SGVsbG8sIFdvcmxkISBUaGlzIGlzIGEgdGVzdCBzdHJpbmcgZm9yIEJhc2U2NCBlbmNvZGluZy4=',
    seoH1: 'Base64 Encoder & Decoder — Encode and Decode Base64 Online Free',
    seoExtra: {
      comparisonTitle: 'Base64 vs Plain Text',
      comparisonRows: [
        { label: 'Characters Used', left: 'A-Z, a-z, 0-9, +, /, = (64 chars)', right: 'Full ASCII/Unicode range' },
        { label: 'Size', left: '~33% larger than original', right: 'Original size' },
        { label: 'Binary Safe', left: 'Yes — any binary data can be encoded', right: 'No — binary data may be corrupted' },
        { label: 'Transport Safe', left: 'Safe for email, URLs, JSON', right: 'May break in certain transports' },
        { label: 'Encryption', left: 'No — Base64 is encoding, not encryption', right: 'N/A' },
      ],
      commonErrors: [
        'Base64 is encoding, not encryption — do not use it to protect sensitive data',
        'Invalid Base64 strings cause decode errors — ensure the input has valid characters and correct padding',
        'Line breaks in Base64 strings may cause issues — remove them before decoding',
        'Non-ASCII characters require UTF-8 encoding before Base64 encoding',
        'Missing padding characters (=) at the end may produce incorrect decode results',
      ],
      useCases: [
        'Encoding images or files for embedding in HTML data URIs',
        'Encoding binary attachments for email (MIME) transport',
        'Creating Base64-encoded API authentication tokens',
        'Encoding data for safe inclusion in JSON strings',
        'Debugging encoded values in JWT tokens, cookies, and API headers',
      ],
      longDescription: 'Base64 is a binary-to-text encoding scheme that converts binary data into a string of printable ASCII characters. It uses a 64-character alphabet (A-Z, a-z, 0-9, +, /) plus = for padding. Base64 encoding is essential in web development for embedding binary data in text-based formats like HTML, CSS, JSON, and email. Common use cases include data URIs for inline images, MIME encoding for email attachments, encoding binary API payloads, and debugging JWT tokens. Our encoder handles full UTF-8 text by first converting multi-byte characters to their byte representation before encoding. The decoder reverses this process, properly handling UTF-8 byte sequences. Base64 encoding increases data size by approximately 33%, which is the trade-off for transport safety. Remember that Base64 is not encryption — it is a reversible encoding scheme that provides no security.',
    },
    faq: [
      {
        q: 'What is Base64 encoding?',
        a: 'Base64 is a binary-to-text encoding scheme that represents binary data as printable ASCII characters using a 64-character alphabet. It is commonly used in emails, data URIs, API tokens, and JWT.',
      },
      {
        q: 'How do I switch between encode and decode mode?',
        a: 'Use the mode toggle (Encode/Decode) above the editor. In Encode mode, your input is plain text and the output is Base64. In Decode mode, the input is Base64 and the output is plain text.',
      },
      {
        q: 'Does this tool support UTF-8 characters?',
        a: 'Yes. The tool uses the TextEncoder and TextDecoder APIs to properly handle multi-byte UTF-8 characters including emojis, Chinese characters, Arabic text, and other Unicode content.',
      },
      {
        q: 'Is Base64 the same as encryption?',
        a: 'No. Base64 is encoding, not encryption. Anyone can decode a Base64 string without any key. Never use Base64 to protect sensitive data — use proper encryption algorithms like AES instead.',
      },
      {
        q: 'Why does Base64 make the data larger?',
        a: 'Base64 encoding represents every 3 bytes of input as 4 ASCII characters, resulting in approximately 33% size increase. This is the trade-off for making binary data safe to transmit through text-based protocols.',
      },
    ],
    relatedTools: ['json-formatter', 'json-minifier', 'json-validator'],
  },
  // ─── JSON Cluster (promoted / new) ─────────────────────────────
  {
    id: 'json-to-csv',
    name: 'JSON to CSV',
    route: '/json-to-csv',
    category: 'json',
    description: 'Convert JSON array or object to CSV format. Supports nested objects and arrays.',
    shortDescription: 'Convert JSON to CSV',
    icon: '⇄',
    keywords: ['json', 'csv', 'convert', 'export', 'converter'],
    sampleInput: '[{"name":"John","age":30},{"name":"Jane","age":25}]',
    sampleOutput: 'name,age\nJohn,30\nJane,25',
    seoH1: 'JSON to CSV Converter — Convert JSON to CSV Online Free',
    seoExtra: {
      comparisonTitle: 'JSON vs CSV',
      comparisonRows: [],
      commonErrors: [],
      useCases: ['Export JSON API data to spreadsheet format', 'Convert database exports to CSV'],
      longDescription: 'Convert JSON data to CSV format for use in spreadsheets and data analysis tools.',
    },
    faq: [
      { q: 'How does JSON to CSV work?', a: 'The first object or array element defines the headers. Each subsequent object maps to a row with values for each header.' },
    ],
    relatedTools: ['csv-to-json', 'json-formatter', 'json-to-yaml'],
  },
  {
    id: 'json-to-yaml',
    name: 'JSON to YAML',
    route: '/json-to-yaml',
    category: 'json',
    description: 'Convert JSON to YAML format. Preserves structure with readable indentation.',
    shortDescription: 'Convert JSON to YAML',
    icon: '⇄',
    keywords: ['json', 'yaml', 'convert', 'export', 'converter'],
    sampleInput: '{"name":"John","age":30}',
    sampleOutput: 'name: John\nage: 30',
    seoH1: 'JSON to YAML Converter — Convert JSON to YAML Online Free',
    seoExtra: {
      comparisonTitle: 'JSON vs YAML',
      comparisonRows: [],
      commonErrors: [],
      useCases: ['Convert API responses to config files', 'Migrate JSON configs to YAML'],
      longDescription: 'Convert JSON data to YAML for configuration files and readable data formats.',
    },
    faq: [
      { q: 'How does JSON to YAML work?', a: 'The tool parses your JSON and outputs equivalent YAML with proper indentation and syntax.' },
    ],
    relatedTools: ['yaml-to-json', 'json-formatter', 'yaml-formatter'],
  },
  {
    id: 'csv-to-json',
    name: 'CSV to JSON',
    route: '/csv-to-json',
    category: 'json',
    description: 'Parse CSV and convert to JSON array. First row becomes object keys.',
    shortDescription: 'Convert CSV to JSON',
    icon: '⇄',
    keywords: ['csv', 'json', 'convert', 'import', 'converter'],
    sampleInput: 'name,age\nJohn,30\nJane,25',
    sampleOutput: '[{"name":"John","age":"30"},{"name":"Jane","age":"25"}]',
    seoH1: 'CSV to JSON Converter — Convert CSV to JSON Online Free',
    seoExtra: {
      comparisonTitle: 'CSV vs JSON',
      comparisonRows: [],
      commonErrors: [],
      useCases: ['Import spreadsheet data to APIs', 'Convert exports to JSON format'],
      longDescription: 'Parse CSV files and convert to JSON arrays with headers as keys.',
    },
    faq: [
      { q: 'How does CSV to JSON work?', a: 'The first row defines property names. Each subsequent row becomes an object with those keys.' },
    ],
    relatedTools: ['json-to-csv', 'json-formatter', 'json-to-yaml'],
  },
  {
    id: 'json-diff',
    name: 'JSON Diff',
    route: '/json-diff',
    category: 'json',
    description: 'Compare two JSON objects and see differences. Paste both JSON blobs separated by "---" on its own line.',
    shortDescription: 'Compare two JSON objects',
    icon: '⟷',
    keywords: ['json diff', 'json compare', 'compare json', 'json difference'],
    sampleInput: '{"name":"John","age":30}\n---\n{"name":"John","age":31,"city":"NYC"}',
    sampleOutput: '- age: 30\n+ age: 31\n+ city: "NYC"',
    seoH1: 'JSON Diff — Compare Two JSON Objects Online Free',
    seoExtra: {
      comparisonTitle: 'JSON Diff Output',
      comparisonRows: [
        { label: '+', left: 'Added in second JSON', right: '' },
        { label: '-', left: 'Removed from first JSON', right: '' },
        { label: '~', left: 'Changed between the two', right: '' },
      ],
      commonErrors: ['Use "---" on its own line to separate the two JSON objects', 'Both parts must be valid JSON'],
      useCases: ['Compare API responses', 'Diff config file versions', 'Find changes in JSON exports'],
      longDescription: 'JSON Diff compares two JSON objects and highlights added, removed, and changed keys. Paste the first JSON, then "---" on its own line, then the second JSON. The tool outputs a readable diff: + for added keys, - for removed, ~ for changed values. Nested objects are compared recursively. Use it to compare API responses, config versions, or any JSON data. All processing runs in your browser.',
    },
    faq: [
      { q: 'How do I use JSON Diff?', a: 'Paste the first JSON object, then "---" on its own line, then the second JSON object. Click Run to see the differences.' },
      { q: 'What does +, -, and ~ mean?', a: '+ means the key was added in the second JSON, - means it was removed, ~ means the value changed.' },
      { q: 'Does it support nested objects?', a: 'Yes. Nested objects are compared recursively, and differences are shown with dot notation paths.' },
      { q: 'Is my data sent to a server?', a: 'No. The diff runs entirely in your browser. Your JSON never leaves your device.' },
      { q: 'Can I compare arrays?', a: 'Arrays are compared as whole values. If they differ, the change is shown. For detailed array diffing, consider flattening to objects first.' },
    ],
    relatedTools: ['json-formatter', 'json-validator', 'json-viewer'],
  },
  {
    id: 'json-schema-generator',
    name: 'JSON Schema Generator',
    route: '/json-schema-generator',
    category: 'json',
    description: 'Infer JSON Schema from sample JSON. Generates type, properties, and required fields.',
    shortDescription: 'Generate JSON Schema from JSON',
    icon: '◈',
    keywords: ['json', 'schema', 'generate', 'infer', 'validator'],
    sampleInput: '{"name":"John","age":30}',
    sampleOutput: '{"type":"object","properties":{"name":{"type":"string"},"age":{"type":"number"}},"required":["name","age"]}',
    seoH1: 'JSON Schema Generator — Infer Schema from JSON Online Free',
    seoExtra: {
      comparisonTitle: 'JSON vs JSON Schema',
      comparisonRows: [],
      commonErrors: [],
      useCases: ['Generate schemas for API validation', 'Document data structures'],
      longDescription: 'Analyze JSON sample data and generate a JSON Schema that describes its structure.',
    },
    faq: [
      { q: 'What is JSON Schema?', a: 'JSON Schema is a vocabulary for annotating and validating JSON documents.' },
    ],
    relatedTools: ['json-formatter', 'json-validator', 'json-to-xml'],
  },
  // ─── YAML Cluster ─────────────────────────────────────────────
  {
    id: 'yaml-formatter',
    name: 'YAML Formatter',
    route: '/yaml-formatter',
    category: 'yaml',
    description: 'Format and beautify YAML with consistent 2-space indentation.',
    shortDescription: 'Format YAML with proper indentation',
    icon: 'Y',
    keywords: ['yaml', 'formatter', 'beautify', 'prettify', 'format'],
    sampleInput: 'name: John\nage: 30\naddress:\n  city: NYC',
    sampleOutput: 'name: John\nage: 30\naddress:\n  city: NYC',
    seoH1: 'YAML Formatter — Beautify YAML Online Free',
    seoExtra: {
      comparisonTitle: 'Formatted vs Compact YAML',
      comparisonRows: [],
      commonErrors: [],
      useCases: ['Format config files', 'Clean up YAML output'],
      longDescription: 'Format YAML files with proper indentation and line breaks.',
    },
    faq: [
      { q: 'What is YAML?', a: 'YAML is a human-readable data serialization format often used for configuration files.' },
    ],
    relatedTools: ['yaml-to-json', 'json-to-yaml', 'json-formatter'],
  },
  {
    id: 'yaml-to-json',
    name: 'YAML to JSON',
    route: '/yaml-to-json',
    category: 'yaml',
    description: 'Convert YAML to JSON. Parse YAML and output equivalent JSON.',
    shortDescription: 'Convert YAML to JSON',
    icon: '⇄',
    keywords: ['yaml', 'json', 'convert', 'converter'],
    sampleInput: 'name: John\nage: 30',
    sampleOutput: '{\n  "name": "John",\n  "age": 30\n}',
    seoH1: 'YAML to JSON Converter — Convert YAML to JSON Online Free',
    seoExtra: {
      comparisonTitle: 'YAML vs JSON',
      comparisonRows: [],
      commonErrors: [],
      useCases: ['Use YAML configs in JavaScript', 'Convert Kubernetes manifests to JSON'],
      longDescription: 'Convert YAML configuration to JSON for use in APIs and applications.',
    },
    faq: [
      { q: 'How does YAML to JSON work?', a: 'The tool parses YAML using js-yaml and outputs the equivalent JSON structure.' },
    ],
    relatedTools: ['json-to-yaml', 'yaml-formatter', 'json-formatter'],
  },
  // ─── XML Cluster ──────────────────────────────────────────────
  {
    id: 'xml-formatter',
    name: 'XML Formatter',
    route: '/xml-formatter',
    category: 'xml',
    description: 'Format XML with proper indentation for readability.',
    shortDescription: 'Format and beautify XML',
    icon: '<>',
    keywords: ['xml', 'formatter', 'beautify', 'prettify', 'format'],
    sampleInput: '<root><item>a</item><item>b</item></root>',
    sampleOutput: '<root>\n  <item>a</item>\n  <item>b</item>\n</root>',
    seoH1: 'XML Formatter — Beautify XML Online Free',
    seoExtra: {
      comparisonTitle: 'Formatted vs Minified XML',
      comparisonRows: [],
      commonErrors: [],
      useCases: ['Format SOAP responses', 'Read XML config files'],
      longDescription: 'Format XML documents with proper indentation for easy reading.',
    },
    faq: [
      { q: 'What is XML?', a: 'XML is a markup language for storing and transporting structured data.' },
    ],
    relatedTools: ['xml-validator', 'xml-to-json', 'json-to-xml'],
  },
  {
    id: 'xml-validator',
    name: 'XML Validator',
    route: '/xml-validator',
    category: 'xml',
    description: 'Validate XML syntax. Check for well-formed XML and report errors.',
    shortDescription: 'Validate XML syntax',
    icon: '✓',
    keywords: ['xml', 'validator', 'validate', 'check', 'syntax'],
    sampleInput: '<root><item>test</item></root>',
    sampleOutput: '✓ Valid XML',
    seoH1: 'XML Validator — Validate XML Online Free',
    seoExtra: {
      comparisonTitle: 'XML Validator vs XML Formatter',
      comparisonRows: [],
      commonErrors: [],
      useCases: ['Debug XML responses', 'Verify config files'],
      longDescription: 'Validate XML documents for correct syntax and structure.',
    },
    faq: [
      { q: 'What does XML validation check?', a: 'It checks for well-formed XML: balanced tags, proper escaping, valid structure.' },
    ],
    relatedTools: ['xml-formatter', 'xml-to-json', 'json-validator'],
  },
  {
    id: 'xml-to-json',
    name: 'XML to JSON',
    route: '/xml-to-json',
    category: 'xml',
    description: 'Convert XML to JSON. Parse XML and output equivalent JSON structure.',
    shortDescription: 'Convert XML to JSON',
    icon: '⇄',
    keywords: ['xml', 'json', 'convert', 'converter'],
    sampleInput: '<root><name>John</name><age>30</age></root>',
    sampleOutput: '{\n  "root": {\n    "name": "John",\n    "age": "30"\n  }\n}',
    seoH1: 'XML to JSON Converter — Convert XML to JSON Online Free',
    seoExtra: {
      comparisonTitle: 'XML vs JSON',
      comparisonRows: [],
      commonErrors: [],
      useCases: ['Convert SOAP to REST', 'Process XML in JavaScript'],
      longDescription: 'Convert XML documents to JSON for use in modern applications.',
    },
    faq: [
      { q: 'How does XML to JSON work?', a: 'Elements become objects, text content is preserved, attributes are prefixed with @.' },
    ],
    relatedTools: ['json-to-xml', 'xml-formatter', 'json-formatter'],
  },
  // ─── Security Cluster ─────────────────────────────────────────
  {
    id: 'jwt-decoder',
    name: 'JWT Decoder',
    route: '/jwt-decoder',
    category: 'security',
    description: 'Decode JWT tokens. View header and payload as formatted JSON.',
    shortDescription: 'Decode JWT tokens',
    icon: '🔓',
    keywords: ['jwt', 'decode', 'token', 'header', 'payload'],
    sampleInput: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIn0.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c',
    sampleOutput: '{"header":{"alg":"HS256","typ":"JWT"},"payload":{"sub":"1234567890","name":"John Doe"}}',
    seoH1: 'JWT Decoder — Decode JWT Tokens Online Free',
    seoExtra: {
      comparisonTitle: 'JWT Structure',
      comparisonRows: [],
      commonErrors: [],
      useCases: ['Debug authentication tokens', 'Inspect token claims'],
      longDescription: 'Decode JWT (JSON Web Token) header and payload without verifying the signature.',
    },
    faq: [
      { q: 'Does this verify the JWT signature?', a: 'No. This tool only decodes the base64url-encoded header and payload for inspection.' },
    ],
    relatedTools: ['base64', 'json-formatter', 'json-validator'],
  },
  // ─── High-traffic SEO tools ─────────────────────────────────────
  {
    id: 'json-viewer',
    name: 'JSON Viewer',
    route: '/json-viewer',
    category: 'json',
    description: 'View and explore JSON data with an interactive tree. Format, validate, and navigate nested structures online.',
    shortDescription: 'View JSON in tree format',
    icon: '👁',
    keywords: ['json viewer', 'json tree', 'json explorer', 'view json online'],
    sampleInput: '{"user":{"name":"John","roles":["admin","user"]}}',
    sampleOutput: '{\n  "user": {\n    "name": "John",\n    "roles": ["admin", "user"]\n  }\n}',
    seoH1: 'JSON Viewer — View & Explore JSON Online Free',
    seoExtra: {
      comparisonTitle: 'JSON Viewer vs Plain Text',
      comparisonRows: [
        { label: 'Structure', left: 'Collapsible tree view', right: 'Flat text' },
        { label: 'Navigation', left: 'Expand/collapse nodes', right: 'Scroll only' },
        { label: 'Syntax', left: 'Highlighted + validated', right: 'Raw text' },
      ],
      commonErrors: ['Invalid JSON prevents tree rendering', 'Ensure proper quote and comma usage'],
      useCases: ['Explore API responses', 'Debug nested configs', 'Inspect JSON structure'],
      longDescription: 'JSON Viewer displays your JSON data as an interactive, collapsible tree. Paste minified or formatted JSON and use the Tree view in the output panel to expand and collapse objects and arrays. This makes it easy to navigate large JSON structures without scrolling through raw text. The tool formats your JSON with proper indentation and validates syntax, so you can quickly spot structural issues. All processing runs in your browser—your data never leaves your device.',
    },
    faq: [
      { q: 'What is a JSON viewer?', a: 'A JSON viewer formats and displays JSON in a navigable tree structure so you can expand and collapse nested objects and arrays.' },
      { q: 'How do I view JSON in tree format?', a: 'Paste your JSON into the editor, click Run, then toggle the Tree button in the output panel to see the collapsible view.' },
      { q: 'Can I view invalid JSON?', a: 'No. The viewer requires valid JSON. Use our JSON Validator to fix syntax errors first.' },
      { q: 'Is my JSON data secure?', a: 'Yes. All processing happens in your browser. No data is sent to any server.' },
      { q: 'What is JSON?', a: 'JSON (JavaScript Object Notation) is a lightweight data format used for APIs, configs, and data storage.' },
    ],
    relatedTools: ['json-formatter', 'json-validator', 'json-to-xml'],
  },
  {
    id: 'json-parser',
    name: 'JSON Parser',
    route: '/json-parser',
    category: 'json',
    description: 'Parse JSON strings online. Validate syntax, format output, and get structured results instantly.',
    shortDescription: 'Parse and validate JSON online',
    icon: '⚙',
    keywords: ['json parser', 'parse json', 'json parser online', 'parse json string'],
    sampleInput: '{"key":"value","count":42}',
    sampleOutput: '{\n  "key": "value",\n  "count": 42\n}',
    seoH1: 'JSON Parser — Parse & Validate JSON Online Free',
    seoExtra: {
      comparisonTitle: 'JSON Parser vs Manual Parsing',
      comparisonRows: [
        { label: 'Speed', left: 'Instant in-browser', right: 'Manual debugging' },
        { label: 'Errors', left: 'Clear error messages', right: 'Obscure stack traces' },
        { label: 'Output', left: 'Formatted + validated', right: 'Depends on code' },
      ],
      commonErrors: ['Trailing commas', 'Unquoted keys', 'Single quotes', 'Missing brackets'],
      useCases: ['Parse API responses', 'Validate config files', 'Debug JSON strings'],
      longDescription: 'The JSON Parser parses your JSON string and returns formatted, validated output. It uses the native browser JSON engine to ensure compatibility with standard JSON. If parsing fails, you get a clear error message to fix the issue. The parser handles all JSON types—objects, arrays, strings, numbers, booleans, and null. Use it to quickly verify JSON from APIs, configs, or logs. Everything runs client-side for speed and privacy.',
    },
    faq: [
      { q: 'What is a JSON parser?', a: 'A JSON parser reads a JSON string and converts it into a structured format, validating syntax and reporting errors.' },
      { q: 'How do I parse JSON online?', a: 'Paste your JSON string into the editor and click Run. Valid JSON will be formatted; invalid JSON will show an error.' },
      { q: 'Does the parser support all JSON types?', a: 'Yes. Objects, arrays, strings, numbers, booleans, and null are all supported.' },
      { q: 'Why does my JSON fail to parse?', a: 'Common causes: trailing commas, unquoted keys, single quotes instead of double quotes, or missing brackets.' },
      { q: 'Is the JSON parser free?', a: 'Yes. The tool is free, runs in your browser, and requires no sign-up.' },
    ],
    relatedTools: ['json-validator', 'json-formatter', 'json-viewer'],
  },
  {
    id: 'json-pretty-print',
    name: 'JSON Pretty Print',
    route: '/json-pretty-print',
    category: 'json',
    description: 'Pretty print JSON with consistent indentation. Make minified JSON readable in one click.',
    shortDescription: 'Pretty print JSON with indentation',
    icon: '✨',
    keywords: ['json pretty print', 'pretty print json', 'json beautifier', 'format json'],
    sampleInput: '{"a":1,"b":[2,3],"c":{"d":4}}',
    sampleOutput: '{\n  "a": 1,\n  "b": [2, 3],\n  "c": {\n    "d": 4\n  }\n}',
    seoH1: 'JSON Pretty Print — Beautify JSON Online Free',
    seoExtra: {
      comparisonTitle: 'Pretty Print vs Minified',
      comparisonRows: [
        { label: 'Readability', left: 'Indented, one item per line', right: 'Single line' },
        { label: 'Size', left: 'Larger', right: 'Smallest' },
        { label: 'Use', left: 'Debugging, editing', right: 'APIs, storage' },
      ],
      commonErrors: ['Invalid JSON', 'Trailing commas', 'Unquoted keys'],
      useCases: ['Read API responses', 'Edit config files', 'Debug JSON data'],
      longDescription: 'JSON Pretty Print transforms minified or compressed JSON into a human-readable format with 2-space indentation and line breaks. Paste any valid JSON—whether from an API, log file, or config—and get clean output instantly. The tool preserves all data and structure while improving readability. Perfect for development and debugging. All processing is client-side.',
    },
    faq: [
      { q: 'What is pretty print JSON?', a: 'Pretty printing adds indentation and line breaks to JSON so it is easy to read and edit.' },
      { q: 'What indentation does it use?', a: '2 spaces per nesting level, which is a common standard.' },
      { q: 'Does it change my data?', a: 'No. Only whitespace is added. Data and structure remain identical.' },
      { q: 'Can I pretty print invalid JSON?', a: 'No. Fix syntax errors first with our JSON Validator.' },
      { q: 'Is it free?', a: 'Yes. Free, no sign-up, runs entirely in your browser.' },
    ],
    relatedTools: ['json-formatter', 'json-minifier', 'json-viewer'],
  },
  {
    id: 'html-formatter',
    name: 'HTML Formatter',
    route: '/html-formatter',
    category: 'markup',
    description: 'Format and beautify HTML with proper indentation. Make minified HTML readable online.',
    shortDescription: 'Format and beautify HTML',
    icon: '<>',
    keywords: ['html formatter', 'format html', 'html beautifier', 'html formatter online'],
    sampleInput: '<div><span>Hello</span><p>World</p></div>',
    sampleOutput: '<div>\n  <span>Hello</span>\n  <p>World</p>\n</div>',
    seoH1: 'HTML Formatter — Beautify HTML Online Free',
    seoExtra: {
      comparisonTitle: 'Formatted vs Minified HTML',
      comparisonRows: [
        { label: 'Readability', left: 'Indented tags', right: 'Single line' },
        { label: 'Editing', left: 'Easy to modify', right: 'Hard to read' },
        { label: 'Size', left: 'Larger', right: 'Smaller' },
      ],
      commonErrors: ['Unclosed tags', 'Invalid nesting', 'Special characters in attributes'],
      useCases: ['Format minified HTML', 'Prepare HTML for review', 'Debug markup structure'],
      longDescription: 'The HTML Formatter adds proper indentation and line breaks to minified or compact HTML. Paste your HTML—whether from a CMS, template, or scraper—and get clean, readable output. The tool parses the HTML and reformats it with consistent indentation. Useful for code review, debugging, and learning HTML structure. All processing runs in your browser.',
    },
    faq: [
      { q: 'What is an HTML formatter?', a: 'An HTML formatter adds indentation and line breaks to HTML to make it readable.' },
      { q: 'Does it fix invalid HTML?', a: 'The browser parser may correct some errors, but malformed HTML can produce unexpected output.' },
      { q: 'Will formatting change how the page renders?', a: 'No. Whitespace changes do not affect HTML rendering.' },
      { q: 'Is my HTML sent to a server?', a: 'No. Formatting happens entirely in your browser.' },
      { q: 'Can I format large HTML files?', a: 'Yes. The tool handles large inputs limited only by browser memory.' },
    ],
    relatedTools: ['xml-formatter', 'json-formatter', 'xml-validator'],
  },
  {
    id: 'url-encode',
    name: 'URL Encoder',
    route: '/url-encode',
    category: 'encoding',
    description: 'Encode text for use in URLs. Convert spaces and special characters to percent-encoded format.',
    shortDescription: 'Encode text for URLs',
    icon: '%',
    keywords: ['url encode', 'url encoder', 'percent encode', 'encode url'],
    sampleInput: 'Hello World! How are you?',
    sampleOutput: 'Hello%20World!%20How%20are%20you%3F',
    seoH1: 'URL Encoder — Encode Text for URLs Online Free',
    seoExtra: {
      comparisonTitle: 'URL Encoded vs Plain Text',
      comparisonRows: [
        { label: 'Spaces', left: '%20', right: ' ' },
        { label: 'Special chars', left: '%XX hex', right: 'Raw character' },
        { label: 'Use', left: 'Query params, paths', right: 'Display only' },
      ],
      commonErrors: ['Double encoding', 'Wrong character set', 'Missing encoding in APIs'],
      useCases: ['Build query strings', 'Encode form data', 'Create safe URLs'],
      longDescription: 'URL Encoder converts text into percent-encoded format for safe use in URLs. Spaces become %20, special characters like & and = become %26 and %3D. This is essential when building query strings, passing parameters in URLs, or encoding form data. The tool uses the standard encodeURIComponent function. All encoding happens in your browser.',
    },
    faq: [
      { q: 'What is URL encoding?', a: 'URL encoding converts characters into %XX format so they can be safely used in URLs.' },
      { q: 'When should I use URL encoding?', a: 'When building query strings, passing parameters in URLs, or encoding form data for submission.' },
      { q: 'What about spaces?', a: 'Spaces are encoded as %20 (or + in application/x-www-form-urlencoded).' },
      { q: 'Is this the same as Base64?', a: 'No. URL encoding is percent-encoding; Base64 is a different binary-to-text encoding.' },
      { q: 'Is my data secure?', a: 'Yes. Encoding runs in your browser. No data is sent to any server.' },
    ],
    relatedTools: ['url-decode', 'base64', 'json-formatter'],
  },
  {
    id: 'url-decode',
    name: 'URL Decoder',
    route: '/url-decode',
    category: 'encoding',
    description: 'Decode URL-encoded strings. Convert percent-encoded text back to plain text.',
    shortDescription: 'Decode URL-encoded strings',
    icon: '%',
    keywords: ['url decode', 'url decoder', 'percent decode', 'decode url'],
    sampleInput: 'Hello%20World!%20How%20are%20you%3F',
    sampleOutput: 'Hello World! How are you?',
    seoH1: 'URL Decoder — Decode URL-Encoded Text Online Free',
    seoExtra: {
      comparisonTitle: 'Encoded vs Decoded',
      comparisonRows: [
        { label: '%20', left: 'Encoded space', right: ' ' },
        { label: '%3F', left: 'Encoded ?', right: '?' },
        { label: 'Use', left: 'In URLs', right: 'Readable text' },
      ],
      commonErrors: ['Invalid % sequence', 'Double-encoded input', 'Malformed hex'],
      useCases: ['Decode query params', 'Read encoded URLs', 'Debug URL issues'],
      longDescription: 'URL Decoder reverses percent-encoding. Paste a URL-encoded string and get the original text. Handles %20 (space), %2B (+), and all standard percent-encoded sequences. Useful when debugging URLs, parsing query parameters, or understanding encoded data. Runs entirely in your browser.',
    },
    faq: [
      { q: 'What is URL decoding?', a: 'URL decoding converts percent-encoded sequences (e.g. %20) back to their original characters.' },
      { q: 'What does %20 mean?', a: '%20 is the encoded form of a space character.' },
      { q: 'Why does decoding fail?', a: 'Invalid % sequences (e.g. %2G) or truncated input can cause errors.' },
      { q: 'Does it handle + as space?', a: 'Yes. Plus signs are decoded as spaces, per application/x-www-form-urlencoded.' },
      { q: 'Is it free?', a: 'Yes. Free, no sign-up, 100% client-side.' },
    ],
    relatedTools: ['url-encode', 'base64', 'json-formatter'],
  },
  {
    id: 'base64-encode',
    name: 'Base64 Encoder',
    route: '/base64-encode',
    category: 'encoding',
    description: 'Encode text or binary data to Base64. Safe for URLs, JSON, and email.',
    shortDescription: 'Encode to Base64',
    icon: 'B64',
    keywords: ['base64 encode', 'base64 encoder', 'encode base64', 'base64 encode online'],
    sampleInput: 'Hello, World!',
    sampleOutput: 'SGVsbG8sIFdvcmxkIQ==',
    seoH1: 'Base64 Encoder — Encode to Base64 Online Free',
    seoExtra: {
      comparisonTitle: 'Base64 vs Plain Text',
      comparisonRows: [
        { label: 'Chars', left: 'A-Z, a-z, 0-9, +, /', right: 'Full Unicode' },
        { label: 'Size', left: '~33% larger', right: 'Original' },
        { label: 'Use', left: 'Data URIs, MIME', right: 'Direct storage' },
      ],
      commonErrors: ['Not encryption', 'Binary data encoding', 'Unicode handling'],
      useCases: ['Data URIs', 'API tokens', 'MIME encoding', 'Embed binary in JSON'],
      longDescription: 'Base64 Encoder converts text and binary data into Base64 format. Use it for data URIs, MIME email attachments, API authentication, and embedding binary in JSON. The output uses only safe ASCII characters. UTF-8 text is fully supported. Encoding runs in your browser—no server involvement.',
    },
    faq: [
      { q: 'What is Base64 encoding?', a: 'Base64 converts binary data into printable ASCII characters using a 64-character alphabet.' },
      { q: 'Is Base64 encryption?', a: 'No. Base64 is encoding, not encryption. Anyone can decode it.' },
      { q: 'Does it support UTF-8?', a: 'Yes. Multi-byte characters are properly encoded.' },
      { q: 'Why is the output larger?', a: 'Base64 uses 4 characters for every 3 bytes of input, about 33% size increase.' },
      { q: 'Is it free?', a: 'Yes. Free, no sign-up, runs in your browser.' },
    ],
    relatedTools: ['base64-decode', 'url-encode', 'jwt-decoder'],
  },
  {
    id: 'base64-decode',
    name: 'Base64 Decoder',
    route: '/base64-decode',
    category: 'encoding',
    description: 'Decode Base64 strings to plain text. Reverse Base64 encoding instantly.',
    shortDescription: 'Decode Base64 to text',
    icon: 'B64',
    keywords: ['base64 decode', 'base64 decoder', 'decode base64', 'base64 decode online'],
    sampleInput: 'SGVsbG8sIFdvcmxkIQ==',
    sampleOutput: 'Hello, World!',
    seoH1: 'Base64 Decoder — Decode Base64 Online Free',
    seoExtra: {
      comparisonTitle: 'Base64 vs Decoded',
      comparisonRows: [
        { label: 'Input', left: 'Base64 string', right: 'Plain text' },
        { label: 'Output', left: 'Original data', right: 'N/A' },
        { label: 'Use', left: 'Reverse encoding', right: 'N/A' },
      ],
      commonErrors: ['Invalid characters', 'Missing padding', 'Wrong encoding'],
      useCases: ['Decode data URIs', 'Read JWT payloads', 'Extract embedded data'],
      longDescription: 'Base64 Decoder converts Base64 strings back to their original form. Paste a Base64-encoded string and get the decoded output. Handles UTF-8 text and binary data. Useful for debugging JWT tokens, data URIs, and API responses. All decoding happens in your browser.',
    },
    faq: [
      { q: 'What is Base64 decoding?', a: 'Base64 decoding reverses the encoding process, converting Base64 strings back to original data.' },
      { q: 'Why does decoding fail?', a: 'Invalid characters, incorrect padding, or corrupted input cause failures.' },
      { q: 'Can it decode images?', a: 'It decodes to binary/text. For images, you would need to handle the binary output.' },
      { q: 'Is it secure?', a: 'Decoding runs in your browser. Your data is not sent anywhere.' },
      { q: 'Is it free?', a: 'Yes. Free, no sign-up, 100% client-side.' },
    ],
    relatedTools: ['base64-encode', 'jwt-decoder', 'url-decode'],
  },
];

export const TOOL_MAP = Object.fromEntries(TOOLS.map((t) => [t.id, t]));

export const CATEGORIES = [
  { id: 'json', label: 'JSON Tools' },
  { id: 'yaml', label: 'YAML Tools' },
  { id: 'xml', label: 'XML Tools' },
  { id: 'markup', label: 'Markup' },
  { id: 'security', label: 'Security' },
  { id: 'encoding', label: 'Encoding' },
] as const;
